### ISSUE TITLE
Make run issue

### ISSUE THREAD

**Issue by Juniortheone** [p4lang/switch#106]
I have been using the P4 tutorial just fine but now I run the file and this is the error I'm getting.Any help?
![screenshot from 2019-02-25 13-18-31](https://user-images.githubusercontent.com/44960997/53340137-22e92a00-3900-11e9-9bd9-f8dfc95df54d.png)

**Comment by jafingerhut** [comment]
This repository where you have created this issue is not the one for the P4 tutorials.  I would recommend asking by creating an issue in the p4lang/tutorials repository here: https://github.com/p4lang/tutorials

There is also a P4 Slack channel here: https://p4-lang.slack.com

**Comment by Juniortheone** [comment]
Okay

**Comment by Juniortheone** [comment]
I tried using the p4-lang.slack but it says I need an invitation from the administrator.How do I join?
