### ISSUE TITLE
What's the meaning of 'bd' in "switch.p4"?

### ISSUE THREAD

**Issue by jijinfanhua** [p4lang/switch#112]
Hi,
I am reading the source code of "switch.p4", and there are lots of 'bd', e.g., "ingress_metadata.outer_bd", "ingress_metadata.bd", so what's the meaning of 'bd'? Bridge?

Thanks a lot.

**Comment by vgurevich** [comment]
"bd" stands for "Bridge Domain", which is a generalization of a VLAN concept. Some people also say "Broadcast Domain", which is kind of the same thing.

**Comment by jijinfanhua** [comment]
> "bd" stands for "Bridge Domain", which is a generalization of a VLAN concept. Some people also say "Broadcast Domain", which is kind of the same thing.

Got it! Thanks a lot!
