### ISSUE TITLE
extra configure.ac files

### ISSUE THREAD

**Issue by antoninbas** [p4lang/switch#16]
Could we remove the autogen.sh / configure.ac files in switchapi / switchsai / switchlink? Unless they serve a purpose?

**Comment by antoninbas** [comment]
@srikrishnagopu

**Comment by krambn** [comment]
The original intent was to be able to make/make install api, sai and link in that order individually. Not sure this works as intended in the current directory structure.
@ckbf

**Comment by antoninbas** [comment]
As far as I can tell, these files are not being used. Everything is handled by the root configure.

**Comment by antoninbas** [comment]
Files removed in https://github.com/p4lang/switch/pull/23
