### ISSUE TITLE
same configure error (follow up from #52)

### ISSUE THREAD

**Issue by dajidan** [p4lang/switch#53]
When I ran the configure command, I got the same error as in #52 :

checking bm/pdfixed/pd_common.h usability... no
checking bm/pdfixed/pd_common.h presence... no
checking for bm/pdfixed/pd_common.h... no
configure: error: bmv2 pdfixed headers not found
configure: error: ./configure failed for p4-build

However I do have installed bmv2 according to https://github.com/p4lang/behavioral-model and add --with-pdfixed option.

I can also run sample p4 programs with this installed bmv2. However, the 'configure' file in this switch repo seems not to recognize this. How do I verify that bmv2 has been installed to a standard location so that it can be found?

**Comment by antoninbas** [comment]
The behavioral-model headers get installed under `$(prefix)/include/bm`. If you use the standard location (at least on Ubuntu), the headers should be under `/usr/local/include/bm/`. On my system I have the following:
```
/usr/local/include/bm
├── bm_apps
├── bm_runtime
├── bm_sim
├── pdfixed
├── simple_pre_constants.h
├── SimplePre.h
├── simple_pre_lag_constants.h
├── SimplePreLAG.h
├── simple_pre_lag_types.h
├── simple_pre_types.h
├── simple_switch_constants.h
├── SimpleSwitch.h
├── simple_switch_types.h
├── spdlog
├── standard_constants.h
├── Standard.h
└── standard_types.h
```
Be sure to look out for the `pdfixed` directory.
It is also possible to install the behavioral-model in a non-standard location by running `configure` with `--prefix=<your location>`. If you use the same `--prefix` location for switch, you should have no issue. However, if you use a different one, then you will have to update the patch / include search path / library search path appropriately yourself.

**Comment by steevenlee** [comment]
Something missing in BMv2 guide: 
    sudo make install

**Comment by antoninbas** [comment]
updated bmv2 Readme
