### ISSUE TITLE
Switch readme is missing a step

### ISSUE THREAD

**Issue by rodedzats** [p4lang/switch#86]
Hi,
I followed the readme instructions in order to run switch in bmv2. I installed bmv2 and p4c-bmv2 however the make command exited with an error because there was no rule make all for p4-build. I think that running the command "git submodule update --init --recursive"  (before ./autogen.sh) should be added to the readme (I saw other users having the same problem). 
@tomerdragucki

**Comment by antoninbas** [comment]
Added with 3542a767adb253e466e8df3a630ba1e6768d8caa
